-- This will create a table called "sample",
-- with the column names: id, first_name, surname, and company
-- to the right of each name is the data type associated with it.
CREATE TABLE `sample` (
  `id` mediumint(8) unsigned NOT NULL auto_increment,
  `first_name` varchar(255) default NULL,
  `surname` varchar(255) default NULL,
  `company` varchar(255),
  PRIMARY KEY (`id`)
) AUTO_INCREMENT=1;

INSERT INTO `sample` (`first_name`,`surname`,`company`) VALUES ("Chadwick","Dixon","Cras Institute"),("April","Aguilar","Orci Sem LLC"),("Hadassah","Horn","Adipiscing Associates"),("Megan","Ross","Egestas Industries"),("Noel","Hartman","Aliquet Industries"),("Nola","Huber","Id Limited"),("Kuame","Bennett","Tempus Consulting"),("Kai","Mcdonald","Vel PC"),("Tanya","Boyle","Et Risus LLP"),("Veronica","Mills","Vulputate Corp.");
INSERT INTO `sample` (`first_name`,`surname`,`company`) VALUES ("Alyssa","Gillespie","Phasellus Fermentum Convallis Associates"),("Mary","Byrd","Nulla Corporation"),("Michael","Maldonado","Ultricies Ligula Nullam Foundation"),("Mohammad","Farrell","Sed Institute"),("Reagan","Frye","Malesuada Fames Ac Foundation"),("Courtney","Mcclure","Ipsum Ltd"),("Isaac","French","Nonummy Consulting"),("Lars","Guerrero","Risus In Corporation"),("Baxter","Turner","Tempor Lorem Eget LLC"),("Lamar","Frederick","Adipiscing Elit Aliquam Limited");
INSERT INTO `sample` (`first_name`,`surname`,`company`) VALUES ("Maxine","Benson","Quis Diam Company"),("Solomon","Hanson","Dictum Ultricies Ligula Corporation"),("Rhoda","Shaffer","Molestie Foundation"),("Madonna","Williams","Ipsum PC"),("Amery","Stout","Interdum Feugiat Sed Company"),("Walter","Wiley","Magna Ut Corporation"),("Sophia","Olsen","Nam Ligula Elit PC"),("Theodore","Garza","Amet Ltd"),("Lacey","Wiggins","Mi Duis Risus PC"),("Cyrus","Stevens","Aliquet Libero Integer Foundation");
INSERT INTO `sample` (`first_name`,`surname`,`company`) VALUES ("Wanda","Mcdowell","Sed Dictum Proin PC"),("Rose","Young","Ut Consulting"),("Armand","Marshall","Odio Vel Est Ltd"),("Farrah","Fry","Tempor Augue LLC"),("Cairo","Winters","Velit Limited"),("Tamekah","Santana","Quis Massa Incorporated"),("Beck","Poole","Ac Industries"),("Chaim","Tyler","Facilisis Limited"),("Roary","Barr","Nunc Sed Pede Foundation"),("Jocelyn","Simpson","Tincidunt Consulting");
INSERT INTO `sample` (`first_name`,`surname`,`company`) VALUES ("Phoebe","Shelton","Sed Malesuada LLC"),("Veronica","Gilmore","Odio Semper Cursus Incorporated"),("Knox","Larsen","Purus Foundation"),("Alexandra","Bishop","Volutpat Corporation"),("Sara","Best","Vitae Ltd"),("Dieter","Morris","Luctus Aliquet Associates"),("Lee","Carver","Elementum Company"),("Zenia","Lee","A LLP"),("Constance","Webster","Sapien Company"),("Beck","Vaughan","Integer Vitae Nibh Consulting");
INSERT INTO `sample` (`first_name`,`surname`,`company`) VALUES ("Carissa","Holland","Auctor Incorporated"),("Shoshana","Moon","Nulla Vulputate PC"),("Fallon","Russell","Donec Elementum Associates"),("Jermaine","Hawkins","Vulputate Company"),("Germaine","Barnes","Non Justo Corporation"),("Phoebe","Mathews","Amet Limited"),("Dane","Sherman","Leo Vivamus Nibh Company"),("Iliana","Mccarthy","Quam Vel Sapien Inc."),("Peter","Castillo","Tristique Institute"),("Patrick","Landry","Pede Ultrices A Inc.");
INSERT INTO `sample` (`first_name`,`surname`,`company`) VALUES ("Cairo","Marsh","Metus Sit Amet Institute"),("Carissa","Hudson","Volutpat Nulla Dignissim Incorporated"),("Shea","Jordan","Vitae Erat Vivamus Foundation"),("Rae","Norton","Suspendisse Sagittis Nullam Incorporated"),("Chantale","Page","Nunc Ac Corp."),("Cameran","Santiago","Eu Consulting"),("Quon","Allison","Interdum Ligula Incorporated"),("Gage","Melton","Vulputate LLC"),("Craig","Gallegos","Dolor Vitae Dolor Associates"),("Brady","Dixon","Justo Nec Ltd");
INSERT INTO `sample` (`first_name`,`surname`,`company`) VALUES ("Cally","Mullen","Ante Lectus Institute"),("Mariko","Kemp","Venenatis Lacus Foundation"),("Quynn","Booker","Felis Industries"),("Rose","Patterson","Vitae Purus Gravida Consulting"),("Steel","Cardenas","Vestibulum Mauris Magna Associates"),("Hamish","Morse","Pharetra Felis Company"),("Veda","Bowman","Metus Aenean Incorporated"),("Tara","Dunn","Ligula Aliquam Erat LLP"),("Jennifer","Cox","Magnis Limited"),("Drake","Burns","Nunc Est Mollis Company");
INSERT INTO `sample` (`first_name`,`surname`,`company`) VALUES ("Nicholas","Maynard","Tincidunt Inc."),("Yuli","Bridges","Nulla Industries"),("Zia","Vaughan","Curabitur Egestas Nunc Ltd"),("Moana","Cain","Accumsan Interdum Libero Industries"),("Dominique","Mcneil","Purus Nullam Inc."),("Kyra","York","Lorem Vitae Company"),("Hasad","Koch","Commodo Hendrerit Company"),("Noelani","Welch","Quis Corporation"),("Cleo","Holland","Luctus Company"),("Reuben","Melendez","Semper Pretium Neque Ltd");
INSERT INTO `sample` (`first_name`,`surname`,`company`) VALUES ("Brett","Alford","Nulla Donec Non Incorporated"),("Victor","Rivera","Venenatis LLP"),("Abbot","Daugherty","Magnis Associates"),("Joseph","Allison","Curae; Phasellus Ornare LLC"),("Basia","Barrett","Nunc Company"),("Rhona","Donovan","In Company"),("Abel","Johnston","Tempus Eu Foundation"),("Diana","Orr","Inceptos Hymenaeos LLP"),("Keefe","Becker","Vivamus Rhoncus Limited"),("Shelly","Turner","Est Ltd");
